export enum Actions {
  ADD_HERO,
  DELETE_HERO,
  HERO_SELECTED,
  UPDATE_HERO,
  ADD_WEAPON,
  DELETE_WEAPON,
  WEAPON_SELECTED,
  UPDATE_WEAPON,
  HERO_TO_ARM_SELECTED,
  WEAPON_TO_ARM_SELECTED,
  ADD_ARMED_HERO ,
  DELETE_ARMED_HERO
}
